# Generated by Django 5.2 on 2025-07-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pe_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicengagementannualmonitoring',
            name='year',
            field=models.IntegerField(unique=True),
        ),
    ]
