# Generated by Django 5.2 on 2025-11-20 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizational_area', '0002_alter_organizationalstructure_options'),
        ('pe_management', '0002_alter_publicengagementannualmonitoring_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicengagementevent',
            name='structure',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, to='organizational_area.organizationalstructure', verbose_name='Affiliation structure'),
        ),
    ]
