# Generated by Django 5.2 on 2026-02-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pe_management', '0003_alter_publicengagementevent_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicengagementeventreport',
            name='edited_by_operator',
            field=models.BooleanField(default=False, verbose_name="Modificato dall'operatore"),
        ),
    ]
