# Generated by Django 5.2 on 2026-02-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pe_management', '0004_publicengagementeventreport_edited_by_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicengagementevent',
            name='edited_by_operator',
            field=models.BooleanField(default=False, verbose_name="Modificato dall'operatore"),
        ),
    ]
