# Generated by Django 5.2 on 2026-02-16 10:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pe_management', '0005_publicengagementevent_edited_by_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicengagementannualmonitoring',
            name='end',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='End'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicengagementannualmonitoring',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start'),
            preserve_default=False,
        ),
    ]
