# Generated by Django 5.2 on 2026-02-16 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pe_management', '0006_publicengagementannualmonitoring_end_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicengagementannualmonitoring',
            options={'ordering': ('year',), 'verbose_name': 'Anno di monitoraggio', 'verbose_name_plural': 'Anni di monitoraggio'},
        ),
    ]
