# Generated by Django 5.2 on 2026-02-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pe_management', '0007_alter_publicengagementannualmonitoring_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicengagementeventdata',
            name='project_full_name',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='If the event is linked to a larger project, indicate which one'),
        ),
    ]
