# Generated by Django 5.2 on 2026-03-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pe_management', '0008_publicengagementeventdata_project_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicengagementeventdata',
            name='other_organizing_subject',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Other organization subject'),
        ),
        migrations.AlterField(
            model_name='publicengagementeventdata',
            name='organizing_subject',
            field=models.CharField(choices=[('UniCal', 'University of Calabria (University, Department, or other structure)'), ('Altra università', 'Another university'), ('Altro ente pubblico', 'Another public entity'), ('Ente privato', 'Private entity'), ('Ente del Terzo Settore', 'Third Sector entity'), ('Altro', 'Other (specify)')], default='', max_length=30, verbose_name='Main organizing entity of the initiative'),
        ),
    ]
