# Generated by Django 5.2 on 2026-03-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pe_management', '0009_publicengagementeventdata_other_organizing_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicengagementeventdata',
            name='other_organizing_subject',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Other organizing entity'),
        ),
    ]
