# Generated by Django 5.2 on 2026-03-23 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pe_management', '0010_alter_publicengagementeventdata_other_organizing_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicengagementeventdata',
            name='involved_external_structures',
            field=models.TextField(default='', max_length=500, verbose_name='Other external (not UNICAL) structures involved in organizing/executing the initiative'),
        ),
        migrations.AlterField(
            model_name='publicengagementeventdata',
            name='project_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pe_management.publicengagementevent', verbose_name='If the event is linked to a larger project or event, indicate which one'),
        ),
    ]
