# Generated by Django 5.2 on 2026-03-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pe_management', '0011_publicengagementeventdata_involved_external_structures_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicengagementeventdata',
            name='project_full_name',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='If the event is linked to a larger project or event, indicate which one'),
        ),
    ]
