# Generated by Django 5.2 on 2026-03-23 12:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizational_area', '0002_alter_organizationalstructure_options'),
        ('pe_management', '0012_alter_publicengagementeventdata_project_full_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicengagementeventdata',
            name='involved_external_structures',
            field=models.TextField(default='', max_length=500, verbose_name='Other external (not UniCal) structures involved in organizing/executing the initiative'),
        ),
        migrations.AlterField(
            model_name='publicengagementeventdata',
            name='involved_personnel',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Other UniCal staff members involved in organizing/executing the initiative'),
        ),
        migrations.AlterField(
            model_name='publicengagementeventdata',
            name='involved_structure',
            field=models.ManyToManyField(limit_choices_to={'is_active': True}, to='organizational_area.organizationalstructure', verbose_name='Other UniCal structures involved in organizing/executing the initiative'),
        ),
    ]
