# Generated by Django 5.2 on 2026-04-21 13:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pe_management', '0013_alter_publicengagementeventdata_involved_external_structures_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicengagementeventreport',
            name='budget',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Total budget (in Euro)'),
        ),
        migrations.AlterField(
            model_name='publicengagementeventreport',
            name='participants',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Non-academic audience participating in the initiative or reached via web/social resources, or outreach publications'),
        ),
    ]
