# Generated by Django 5.2 on 2026-05-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pe_management', '0014_alter_publicengagementeventreport_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicengagementeventreport',
            name='budget',
            field=models.CharField(max_length=15, verbose_name='Total budget (in Euro)'),
        ),
        migrations.AlterField(
            model_name='publicengagementeventreport',
            name='participants',
            field=models.CharField(max_length=10, verbose_name='Non-academic audience participating in the initiative or reached via web/social resources, or outreach publications'),
        ),
    ]
