# Generated by Django 5.2 on 2026-10-01 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pe_management', '0018_publicengagementstrategicaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicengagementeventdata',
            name='strategic_action',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='pe_management.publicengagementstrategicaction', verbose_name='If the initiative/activity is linked to an action within the University’s Strategic Plan, select the corresponding one from the drop-down menu.'),
        ),
    ]
