# Generated by Django 5.2 on 2025-04-30 09:34

import django.core.validators
import django.db.models.deletion
import organizational_area.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, unique=True)),
                ('description', models.TextField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'verbose_name': 'Equipment Type',
                'verbose_name_plural': 'Equipments Type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationalStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=254, unique=True)),
                ('slug', models.SlugField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_slug', message='Lo slug deve contenere almeno un carattere alfabetico', regex='^(?=.*[a-zA-Z])')])),
                ('unique_code', models.CharField(blank=True, max_length=254, unique=True)),
                ('description', models.TextField(blank=True, max_length=1024, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('banner', models.ImageField(blank=True, max_length=254, null=True, upload_to=organizational_area.models._logo_upload)),
                ('url', models.CharField(blank=True, max_length=768, null=True)),
            ],
            options={
                'verbose_name': 'Organizational Structure',
                'verbose_name_plural': 'Organizational Structures',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationalStructureFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, unique=True)),
                ('description', models.TextField(blank=True, max_length=768, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Organizational Structure function',
                'verbose_name_plural': 'Organizational Structure functions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationalStructureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, unique=True)),
                ('description', models.TextField(blank=True, max_length=768, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Organizational Structure type',
                'verbose_name_plural': 'Organizational Structure types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationalStructureLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('address', models.CharField(blank=True, max_length=768, null=True)),
                ('coordinate', models.CharField(blank=True, max_length=64, null=True)),
                ('srs', models.CharField(blank=True, help_text='riferimento spaziale coordinate', max_length=13, null=True)),
                ('phone', models.CharField(blank=True, max_length=135, null=True)),
                ('description_short', models.CharField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True, max_length=1024, null=True)),
                ('note', models.TextField(blank=True, help_text='Descrivere lo stato della struttura nella location. Esempio: Momentaneamente chiusa, allagata, problemi lavori in corso, previsioni', max_length=1024, null=True)),
                ('equipment', models.ManyToManyField(to='organizational_area.equipmenttype')),
                ('funcionality', models.ManyToManyField(blank=True, to='organizational_area.organizationalstructurefunction')),
                ('organizational_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizational_area.organizationalstructure')),
            ],
            options={
                'verbose_name': 'Organizational Structure location',
                'verbose_name_plural': 'Organizational Structure locations',
                'ordering': ['organizational_structure'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationalStructureOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=254)),
                ('description', models.TextField(blank=True, max_length=1024, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('organizational_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizational_area.organizationalstructure')),
            ],
            options={
                'verbose_name': 'Organizational Structure Office',
                'verbose_name_plural': 'Organizational Structure Offices',
                'ordering': ['name', 'organizational_structure__name'],
                'unique_together': {('slug', 'organizational_structure')},
            },
        ),
        migrations.CreateModel(
            name='OrganizationalStructureOfficeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('address', models.CharField(blank=True, max_length=768, null=True)),
                ('coordinate', models.CharField(blank=True, max_length=64, null=True)),
                ('srs', models.CharField(blank=True, help_text='riferimento spaziale coordinate', max_length=13, null=True)),
                ('phone', models.CharField(blank=True, max_length=135, null=True)),
                ('description_short', models.CharField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True, max_length=1024, null=True)),
                ('note', models.TextField(blank=True, help_text='Descrivere lo stato della struttura nella location. Esempio: Momentaneamente chiusa, allagata, problemi lavori in corso, previsioni', max_length=1024, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ManyToManyField(to='organizational_area.equipmenttype')),
                ('funcionality', models.ManyToManyField(blank=True, to='organizational_area.organizationalstructurefunction')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizational_area.organizationalstructureoffice')),
            ],
            options={
                'verbose_name': 'Organizational Structure office location',
                'verbose_name_plural': 'Organizational Structure office locations',
                'ordering': ['-create_date'],
            },
        ),
        migrations.AddField(
            model_name='organizationalstructure',
            name='structure_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizational_area.organizationalstructuretype'),
        ),
        migrations.CreateModel(
            name='OrganizationalStructureOfficeEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, max_length=1024, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizational_area.organizationalstructureoffice')),
            ],
            options={
                'verbose_name': 'Organizational Structure Office Employee',
                'verbose_name_plural': 'Organizational Structure Office Employees',
                'ordering': ['-create_date'],
                'unique_together': {('employee', 'office')},
            },
        ),
        migrations.CreateModel(
            name='UserManageOrganizationalStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizational_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizational_area.organizationalstructure')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
                'unique_together': {('user', 'organizational_structure')},
            },
        ),
    ]
