# Generated by Django 5.2 on 2025-07-14 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizational_area', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationalstructure',
            options={'ordering': ['name'], 'verbose_name': 'Struttura organizzativa', 'verbose_name_plural': 'Organizational Structures'},
        ),
    ]
